spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cities_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
token: 'c451d6977f9e43648a3893e8fc66ccb4'
address: 'https://api.openweathermap.org/data/2.5/weather?'